volumes:
    db_volume: {}
    wildfly_persistence: {}

services:
    application_database:
        container_name: app_db
        image: bitnami/postgresql:15.2.0
        environment:
            - POSTGRESQL_DATABASE=enzulode
            - POSTGRESQL_USER=enzulode
            - POSTGRESQL_PASSWORD=password
        volumes:
            - db_volume:/bitnami/postgresql
        ports:
            - "5432:5432"

    app:
        container_name: app
        depends_on:
            - application_database
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - WILDFLY_USERNAME=admindev
            - WILDFLY_PASSWORD=admindev
            - WILDFLY_PUBLIC_LISTEN_ADDRESS=0.0.0.0
            - WILDFLY_MANAGEMENT_LISTEN_ADDRESS=0.0.0.0
        volumes:
            - wildfly_persistence:/bitnami/wildfly
        ports:
            - "8080:8080"
            - "9990:9990"