CREATE SEQUENCE point_id_seq MINVALUE 1 MAXVALUE 9223372036854775807 START 1 INCREMENT 1;

CREATE TABLE point(
    id BIGINT NOT NULL UNIQUE DEFAULT nextval('point_id_seq'),
    x INT NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    r DOUBLE PRECISION NOT NULL,
    result BOOLEAN NOT NULL
);